#
# makefile for the control library
#

#
# define our target library
#
TARGET=input.a

#
# define the source code files
#
SRC = \
	joystick_linux.cpp\
	panel.cpp\
	util.cpp\
	PixyBlock.cpp\
	PixyImpl.cpp\
	PixyTCP.cpp\
	PixyUART.cpp



#
# include a central make file that defines our compilation recipe
#
include ../../makefiles/compilelib.mk
